# -*- coding: utf-8 -*-
"""Emotion Recognition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zQRv5bALvH4eXYzKEaUh_B4PWDEaV9k
"""

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content/drive/MyDrive/audio_speech_actors_01-24"

import os

print("Exists:", os.path.exists(DATASET_PATH))
print("Actor folders:", len(os.listdir(DATASET_PATH)))
print(os.listdir(DATASET_PATH)[:5])

import librosa

sample_file = os.path.join(
    DATASET_PATH,
    "Actor_01",
    os.listdir(os.path.join(DATASET_PATH, "Actor_01"))[0]
)

audio, sr = librosa.load(sample_file, sr=None)

print("File:", sample_file)
print("Sample Rate:", sr)
print("Duration:", len(audio) / sr, "seconds")

import librosa
import numpy as np

mfccs = librosa.feature.mfcc(
    y=audio,
    sr=sr,
    n_mfcc=13
)

print("MFCC Shape:", mfccs.shape)

mfccs_mean = np.mean(mfccs.T, axis=0)

print("Feature Vector Shape:", mfccs_mean.shape)
print(mfccs_mean)

import os
import librosa
import numpy as np
import pandas as pd

emotion_map = {
    "01": "neutral",
    "02": "calm",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "fearful",
    "07": "disgust",
    "08": "surprised"
}

X = []
y = []

count = 0

for actor_folder in os.listdir(DATASET_PATH):

    actor_path = os.path.join(DATASET_PATH, actor_folder)

    if not os.path.isdir(actor_path):
        continue

    for file_name in os.listdir(actor_path):

        if not file_name.endswith(".wav"):
            continue

        file_path = os.path.join(actor_path, file_name)

        audio, sr = librosa.load(file_path, sr=None)

        mfccs = librosa.feature.mfcc(
            y=audio,
            sr=sr,
            n_mfcc=40
        )

        mfcc_mean = np.mean(mfccs, axis=1)
        mfcc_std = np.std(mfccs, axis=1)

        mfcc_features = np.hstack([mfcc_mean, mfcc_std])

        emotion_code = file_name.split("-")[2]
        emotion_label = emotion_map[emotion_code]

        X.append(mfcc_features)
        y.append(emotion_label)

        count += 1

        if count % 100 == 0:
            print(f"Processed {count} files")

X = np.array(X)
y = np.array(y)

print("X shape:", X.shape)
print("y shape:", y.shape)

pd.Series(y).value_counts()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

model = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(
        kernel='rbf',
        C=10,
        gamma='scale',
        class_weight='balanced'
    ))
])

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

disp.plot(xticks_rotation=45)
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

import joblib

joblib.dump(model, "emotion_recognition_model.pkl")

model = joblib.load("emotion_recognition_model.pkl")

import joblib

joblib.dump(
    model,
    "/content/drive/MyDrive/emotion_recognition_model.pkl"
)